name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: build and deploy lambda functions
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
      - run: 
          cd lambdaGet && npm ci
      - run: 
          cd lambdaPost && npm ci
      - run:
          cd lambdaPut && npm ci
      - run:
          cd lambdaDelete && npm ci
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r lambdaGet.zip lambdaGet
      - name: deploy GET
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: lambdaGet
          zip_file: lambdaGet.zip
      - name: deploy POST
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: lambdaGet
          zip_file: lambdaPost.zip
      - name: deploy PUT
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: lambdaGet
          zip_file: lambdaPut.zip
      - name: deploy DELETE
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: lambdaGet
          zip_file: lambdaDelete.zip
